### ISSUE TITLE
Add configuration setting for display

### ISSUE THREAD

**Issue by jar349** [fthuin/yahoofinance-cinnamon-desklet#4]
I wish that I could omit the full name of the stock and just show the ticker symbol because including the full name forces the desklet to be hundreds of pixels wide just to view the numbers (which is what I really care about).

**Comment by fthuin** [comment]
Hello, this is a very good idea, thank you for your contribution. I will improve a lot this desklet during July and I'll add your idea for sure ! If you think about other improvements, do not hesitate to tell me!
