### ISSUE TITLE
Yahoo API has been shutdown

### ISSUE THREAD

**Issue by ase1590** [fthuin/yahoofinance-cinnamon-desklet#7]
Yahoo has shut down their finance API, breaking this desklet. See here: https://www.quora.com/Did-Yahoo-Stock-API-shut-down

A respondent suggests using the Alpha Vantage API: https://www.alphavantage.co/documentation/

**Comment by fthuin** [comment]
Hello,

Thank you for your feedback. This desklet has been moved to [linuxmint/cinnamon-spices-desklets](https://github.com/linuxmint/cinnamon-spices-desklets). Can you create an issue there?

Thank you in advance
